name: Deploy to Test Environment

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Start Test Server
      run: |
        npm start &
        sleep 5

    - name: Verify Deployment
      run: curl -f http://localhost:3000
